# Johantan Meoño

# Problema 5

In [25]:
import numpy as np ## para las matrices y vectores o tensores

In [26]:
import cv2 ## jalando open cv carga y lee imagenes

In [27]:
import sys ## para sacar de memoria o sacar el programa

In [36]:
## creando la fucion
def main(imagen):
    imgStr = imagen ## creo un objeto y le asigno un valor string con el nombre de la imagen
    img = cv2.imread(imgStr) ## creo un nuevo objeto que va a leer la imagen cread en la fila de arriba  
    
    ## tamañao de la imagen
    alto = img.shape[0]
    ancho = img.shape[1]
    canales = img.shape[2]
    
    
    ## matrices 
    ## matriz de azules
    matriz_azul = np.zeros((alto,ancho))
    
    ## mariz de verdes
    matriz_verde = np.zeros((alto,ancho))
    
    ## matiz de rojos
    matriz_roja = np.zeros((alto,ancho))
    
    ## cubo de ceros con las dimensiones de la imagen
    ## se pondra tres pues se trabajara sobre la imagen a colores
    ## cons sus tres canales 
    ## canal 1 es el canal azul
    ## canal 2 es el canal verde
    ## canal 3 es el canal rojo
    
    kernel = np.array ([[0,-1,0],
                        [-1,5,-1],
                        [0,-1,0],
                                ]) ## kenel sharpen 
    
    
    #convolusion = np.zeros((alto+2,ancho+2,3))
    convolusion = np.zeros_like(img)
    
    image_padded = np.zeros((alto + 2, ancho + 2,3))   
    image_padded[1:-1, 1:-1] = img
    
    ## sacando de la imgaen todos los azules, verdes y rojos
    for x in range(img.shape[1]):
        for y in range(img.shape[0]):
            convolusion[i,j]=(kernel*image_padded[y:y+3,x:x+3]).sum() 
            #pixel = img[i,j] ## saco el pixel
            
            #azul = pixel[0] ## al pixel le saco el azul
            #verde = pixel[1] ## al pixel le saco el verde
            #rojo = pixel[2] ## al pixel le saco el rojo
            
            ## llenando las matrices con los colores
            #matriz_azul[i,j] = azul
            #matriz_verde[i,j] = verde
            #matriz_roja[i,j] = rojo
    
    ## subporcionando 
    #for i in range(alto-2):
        #for j in range(ancho-2):
            ## subporciones
            #porcion_azul = matriz_azul[i:i+3,j:j+3]
            #porcion_verde = matriz_verde[i:i+3,j:j+3]
            #porcion_rojo = matriz_roja[i:i+3,j:j+3]
    
    ## productos y sumas 
    #for i in range(alto):
        #for j in range(ancho):           
            ## convolusion
            #azul_convolusion = np.sum(kernel*porcion_azul) ## producto hadamor 
            #verde_convolusion = np.sum(kernel*porcion_verde) ## producto hadamor 
            #rojo_convolusion = np.sum(kernel*porcion_rojo) ## producto hadamor 
            
            
            ## lleando la convolusion 
            #convolusion[i,j] = [azul_convolusion,verde_convolusion,rojo_convolusion]
    
    ## para que fucione el ciclo debo:
    ## bajar la imagen al disco
    cv2.imwrite(str(imagen)+".jpg",convolusion)
    
    
    ## la vuelvo a cargar o leer
    convolusion = cv2.imread(str(imagen)+".jpg")
    
    ## y la muestro
    cv2.imshow("Imagen"+str(imagen),convolusion)
            
    ## comandos para cerrar imagenes
    cv2.waitKey(0) ## espera que apeche tecla para cerrar
    cv2.destroyAllWindows() ## si tngo varias ventas cierra todoas las ventanas a la vez
    sys.exit() ##           

In [37]:
main("doggy.jpg")

SystemExit: 

C:\Users\Johnatan\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2971: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [5]:
matriz = np.zeros((100,20))

In [6]:
matriz.shape


(100, 20)

In [7]:
arreglo = np.array([[3,2],
                    [4,6],])

In [8]:
np.sum(arreglo)

15

https://en.wikipedia.org/wiki/Kernel_(image_processing)

In [9]:
prueba = np.array([[1,2,3,13],
                   [4,5,6,14],
                   [7,8,9,15],
                   [10,11,12,16]])

In [10]:
prueba

array([[ 1,  2,  3, 13],
       [ 4,  5,  6, 14],
       [ 7,  8,  9, 15],
       [10, 11, 12, 16]])

In [11]:
alto = prueba.shape[0]

In [12]:
alto

4

In [13]:
ancho = prueba.shape[1]

In [14]:
ancho

4

In [15]:
prueba[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [16]:
prueba[-5:-2,-4:-1]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
for i in range(alto):
    for j in range(ancho):
        pedazo = prueba[i:i+3,j:j+3]
        print(pedazo)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  3 13]
 [ 5  6 14]
 [ 8  9 15]]
[[ 3 13]
 [ 6 14]
 [ 9 15]]
[[13]
 [14]
 [15]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 5  6 14]
 [ 8  9 15]
 [11 12 16]]
[[ 6 14]
 [ 9 15]
 [12 16]]
[[14]
 [15]
 [16]]
[[ 7  8  9]
 [10 11 12]]
[[ 8  9 15]
 [11 12 16]]
[[ 9 15]
 [12 16]]
[[15]
 [16]]
[[10 11 12]]
[[11 12 16]]
[[12 16]]
[[16]]


In [17]:
for i in range(alto-2):
    for j in range(ancho-2):
        pedazo = prueba[i:i+3,j:j+3]
        print(pedazo)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  3 13]
 [ 5  6 14]
 [ 8  9 15]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 5  6 14]
 [ 8  9 15]
 [11 12 16]]


In [22]:
for i in range(alto):
    for j in range(ancho):
        pedazo = prueba[i-1:i+1,j-1:j+1]
        print(pedazo)

[]
[]
[]
[]
[]
[[1 2]
 [4 5]]
[[2 3]
 [5 6]]
[[ 3 13]
 [ 6 14]]
[]
[[4 5]
 [7 8]]
[[5 6]
 [8 9]]
[[ 6 14]
 [ 9 15]]
[]
[[ 7  8]
 [10 11]]
[[ 8  9]
 [11 12]]
[[ 9 15]
 [12 16]]


In [22]:
for i in range(alto):
    for j in range(ancho):
        pedazo = prueba[i-1:i+1,j-1:j+1]
        print(pedazo)

[]
[]
[]
[]
[]
[[1 2]
 [4 5]]
[[2 3]
 [5 6]]
[[ 3 13]
 [ 6 14]]
[]
[[4 5]
 [7 8]]
[[5 6]
 [8 9]]
[[ 6 14]
 [ 9 15]]
[]
[[ 7  8]
 [10 11]]
[[ 8  9]
 [11 12]]
[[ 9 15]
 [12 16]]


In [30]:
len(pedazo)

2

In [32]:
for i in range(alto):
    for j in range(ancho):
        pedazo = prueba[i:i+3,j:j+3]
        print(pedazo)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[[3]
 [6]
 [9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 5  6]
 [ 8  9]
 [11 12]]
[[ 6]
 [ 9]
 [12]]
[[ 7  8  9]
 [10 11 12]]
[[ 8  9]
 [11 12]]
[[ 9]
 [12]]
[[10 11 12]]
[[11 12]]
[[12]]
