In [30]:
import numpy as np ## para las matrices y vectores o tensores

In [31]:
import cv2 ## jalando open cv carga y lee imagenes

In [66]:
matriz = np.array([[1,2,3],
                   [1,5,6],
                   [1,8,9],
                   [1,255,100],])

In [67]:
matriz

array([[  1,   2,   3],
       [  1,   5,   6],
       [  1,   8,   9],
       [  1, 255, 100]])

In [68]:
ecualizada = np.zeros_like(matriz)

In [69]:
ecualizada

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [70]:
alto = matriz.shape[0]

In [71]:
alto 

4

In [72]:
ancho = matriz.shape[1] 

In [73]:
ancho

3

In [74]:
h = [0.0]*256

In [78]:
for i in range(alto):
    for j in range(ancho):
        h[matriz[i,j]] = h[matriz[i,j]]+1

In [79]:
h

[0.0,
 8.0,
 2.0,
 2.0,
 0.0,
 2.0,
 2.0,
 0.0,
 2.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0

In [84]:
h_norm = np.asarray(h) / (alto*ancho)

In [85]:
h_norm

array([0.        , 0.66666667, 0.16666667, 0.16666667, 0.        ,
       0.16666667, 0.16666667, 0.        , 0.16666667, 0.16666667,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [86]:
h_cum = np.cumsum(h_norm)

In [87]:
h_cum

array([0.        , 0.66666667, 0.83333333, 1.        , 1.        ,
       1.16666667, 1.33333333, 1.33333333, 1.5       , 1.66666667,
       1.66666667, 1.66666667, 1.66666667, 1.66666667, 1.66666667,
       1.66666667, 1.66666667, 1.66666667, 1.66666667, 1.66666667,
       1.66666667, 1.66666667, 1.66666667, 1.66666667, 1.66666667,
       1.66666667, 1.66666667, 1.66666667, 1.66666667, 1.66666667,
       1.66666667, 1.66666667, 1.66666667, 1.66666667, 1.66666667,
       1.66666667, 1.66666667, 1.66666667, 1.66666667, 1.66666667,
       1.66666667, 1.66666667, 1.66666667, 1.66666667, 1.66666667,
       1.66666667, 1.66666667, 1.66666667, 1.66666667, 1.66666667,
       1.66666667, 1.66666667, 1.66666667, 1.66666667, 1.66666667,
       1.66666667, 1.66666667, 1.66666667, 1.66666667, 1.66666667,
       1.66666667, 1.66666667, 1.66666667, 1.66666667, 1.66666667,
       1.66666667, 1.66666667, 1.66666667, 1.66666667, 1.66666667,
       1.66666667, 1.66666667, 1.66666667, 1.66666667, 1.66666

In [88]:
matriz[0,0]

1

In [89]:
for i in range(alto):
    for j in range(ancho):
        pixel = matriz[i,j]    
        ecualizada[i,j] = 256 * h_cum[pixel]

In [90]:
pixel

100

In [91]:
ecualizada

array([[170, 213, 255],
       [170, 298, 341],
       [170, 384, 426],
       [170, 512, 469]])

In [92]:
hh = [0.0]*256

In [93]:
hh

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0

In [94]:
len(hh)

256

https://gist.github.com/bistaumanga/6309599

https://code.tutsplus.com/es/tutorials/histogram-equalization-in-python--cms-30202